# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load environment variables from .env (using 'dotenv' plugin for Vagrant)
Dotenv.load

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Dummy box for AWS
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # Configuration for AWS
  config.vm.provider :aws do |provider, override|

    # AWS authentication
    provider.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    provider.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    # Region and availability zone
    provider.region = "ap-northeast-1"
    provider.availability_zone = "ap-northeast-1a"

    # ID of AMI
    provider.ami = "ami-18869819" # Amazon Linux AMI 2016.03.0 (HVM), SSD Volume Type

    provider.instance_type = "t2.micro"
    provider.instance_ready_timeout = 120
    provider.terminate_on_shutdown = false

    # AWS security group
    provider.security_groups = [ ENV['AWS_SECURITY_GROUP'] ]

    # AWS key pair name to use
    provider.keypair_name = ENV['AWS_KEYPAIR_NAME']

    # SSH
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ENV['AWS_SSH_KEY']

    # Disable synced folders
    override.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
